# Example secret structure - DO NOT commit actual secrets to git
# This should be created via external-secrets, SOPS, or manually
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
type: Opaque
stringData:
  # SSH Public Key for Linux VMs
  ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."

  # Azure Resource ARM IDs (these change per environment)
  subscription_id: "12345678-1234-1234-1234-123456789abc"
  vnet_subnet_arm_id: "/subscriptions/12345678-1234-1234-1234-123456789abc/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/vnet-aks/subnets/aks-subnet"
  control_plane_identity_arm_id: "/subscriptions/12345678-1234-1234-1234-123456789abc/resourceGroups/rg-aks-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dev-control-plane-identity"
  kubelet_identity_arm_id: "/subscriptions/12345678-1234-1234-1234-123456789abc/resourceGroups/rg-aks-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dev-kubelet-identity"
  log_analytics_workspace_arm_id: "/subscriptions/12345678-1234-1234-1234-123456789abc/resourceGroups/rg-monitoring/providers/Microsoft.OperationalInsights/workspaces/law-aks-dev"

  # Identity IDs
  kubelet_identity_client_id: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
  kubelet_identity_object_id: "bbbbbbbb-cccc-dddd-eeee-ffffffffffff"

  # AAD Configuration
  admin_group_object_ids: "cccccccc-dddd-eeee-ffff-aaaaaaaaaaaa"

  # OIDC Issuer URL (obtained from cluster after creation)
  oidc_issuer_url: "https://eastus.oic.prod-aks.azure.com/your-tenant-id/your-issuer-id/"

---
# Production secrets example
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets-prod
  namespace: flux-system
type: Opaque
stringData:
  # Production SSH Public Key
  ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQ..."

  # Production Azure Resource ARM IDs
  subscription_id: "87654321-4321-4321-4321-cba987654321"
  vnet_subnet_arm_id: "/subscriptions/87654321-4321-4321-4321-cba987654321/resourceGroups/rg-network-prod/providers/Microsoft.Network/virtualNetworks/vnet-aks-prod/subnets/aks-subnet"
  control_plane_identity_arm_id: "/subscriptions/87654321-4321-4321-4321-cba987654321/resourceGroups/rg-aks-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-prod-control-plane-identity"
  kubelet_identity_arm_id: "/subscriptions/87654321-4321-4321-4321-cba987654321/resourceGroups/rg-aks-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-prod-kubelet-identity"
  log_analytics_workspace_arm_id: "/subscriptions/87654321-4321-4321-4321-cba987654321/resourceGroups/rg-monitoring-prod/providers/Microsoft.OperationalInsights/workspaces/law-aks-prod"

  # Production Identity IDs
  kubelet_identity_client_id: "dddddddd-eeee-ffff-aaaa-bbbbbbbbbbbb"
  kubelet_identity_object_id: "eeeeeeee-ffff-aaaa-bbbb-cccccccccccc"

  # Production AAD Configuration
  admin_group_object_ids: "ffffffff-aaaa-bbbb-cccc-dddddddddddd"

  # Production OIDC Issuer URL
  oidc_issuer_url: "https://eastus.oic.prod-aks.azure.com/your-tenant-id/your-prod-issuer-id/"