apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aks-infrastructure-dev
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: platform-configs
  path: "./eng/azureserviceoperator-flux/base"
  prune: true
  wait: true

  # Post-build variable substitution using ConfigMaps
  postBuild:
    substitute:
      environment: "dev"
      cluster_name: "aks-dev-eastus-001"
      resource_group_name: "rg-aks-dev-eastus-001"
      location: "eastus"
      kubernetes_version: "1.29"
      cluster_dns_prefix: "aks-dev-eastus-001k8s"

      # Node configuration
      system_node_vm_size: "Standard_D4s_v5"
      system_node_count: "2"
      user_node_vm_size: "Standard_D4s_v5"
      user_node_count: "2"

      # Network configuration
      service_cidr: "10.251.0.0/17"
      dns_service_ip: "10.251.0.10"
      pod_cidr: "10.251.128.0/17"

      # Network profile
      network_plugin: "azure"
      network_plugin_mode: "overlay"
      network_policy: "cilium"
      network_dataplane: "cilium"
      load_balancer_sku: "standard"
      outbound_type: "loadBalancer"
      ip_families: '["IPv4"]'

      # Tags
      project: "arm-ado-migration"
      cost_center: "engineering"
      owner: "platform-team"
      team: "AKSEngineering"
      cmdb_reference: "DEV001"

    substituteFrom:
      - kind: ConfigMap
        name: cluster-variables
        # Use this ConfigMap if it exists, but proceed if it doesn't
        optional: true
      - kind: ConfigMap
        name: cluster-network-variables
        optional: true
      - kind: Secret
        name: cluster-secrets
        # This secret should contain sensitive values like ssh_public_key
        optional: false

  # Health checks
  healthChecks:
    - apiVersion: resources.azure.com/v1api20200601
      kind: ResourceGroup
      name: rg-aks-dev-eastus-001
      namespace: azure-system
    - apiVersion: containerservice.azure.com/v1api20240402preview
      kind: ManagedCluster
      name: aks-dev-eastus-001
      namespace: azure-system

  # Dependencies
  dependsOn:
    - name: azure-service-operator
      namespace: flux-system