apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: ${cluster_name}-workload-identity-credential
  namespace: azure-system
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  owner:
    name: ${cluster_name}-control-plane-identity
  issuer: ${oidc_issuer_url}
  subject: "system:serviceaccount:${workload_namespace:=default}:${service_account_name:=workload-identity-sa}"
  audiences:
    - "api://AzureADTokenExchange"

---
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: ${cluster_name}-external-dns-credential
  namespace: azure-system
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  owner:
    name: ${cluster_name}-control-plane-identity
  issuer: ${oidc_issuer_url}
  subject: "system:serviceaccount:external-dns:external-dns"
  audiences:
    - "api://AzureADTokenExchange"

---
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: ${cluster_name}-cert-manager-credential
  namespace: azure-system
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  owner:
    name: ${cluster_name}-control-plane-identity
  issuer: ${oidc_issuer_url}
  subject: "system:serviceaccount:cert-manager:cert-manager"
  audiences:
    - "api://AzureADTokenExchange"