apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azure-system

resources:
  - resource-group.yaml
  - identity.yaml
  - cluster.yaml
  - federated-credential.yaml

commonLabels:
  app.kubernetes.io/managed-by: azure-service-operator
  app.kubernetes.io/part-of: aks-platform

commonAnnotations:
  config.kubernetes.io/local-config: "true"